version: '3'

services:
  # Servicio de bases de datos
  db:
    image: ${MDB_IMAGE}
    container_name: mariadb_c
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      mi_red:
        ipv4_address: ${MDB_ADDRESS}

  # Servicio de Wordpress
  wordpress:
    image: ${WP_IMAGE}
    container_name: wordpress_c
    restart: always
    depends_on: ['db']
    ports: ['80:80']
    links: ['db:db']
    volumes:
      - './wp_data:/var/html/www'
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      mi_red:
        ipv4_address: ${WP_ADDRESS}

  # Sevicio phpMyAdmin
  phpmyadmin:
    image: ${PMA_IMAGE}
    container_name: phpmyadmin_c
    restart: always
    depends_on: ['db']
    ports: ['12000:80']
    links: ['db:db']
    environment:
      - PMA_HOST=${PMA_HOST}
    networks:
      mi_red:
        ipv4_address: ${PMA_ADDRESS}

volumes:
  db_data:
  
networks:
  mi_red:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_ADDRESS}

